-- ============================================================
-- AI analysis log + chat messages for CRM customer AI panel
-- ============================================================

CREATE SEQUENCE AGRO_AI_ANALYSES_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_AI_CHAT_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE AGRO_AI_ANALYSES (
  ID           NUMBER(10)      NOT NULL,
  CREATED_AT   DATE            DEFAULT SYSDATE NOT NULL,
  CUSTOMER_ID  NUMBER(10)      NOT NULL,
  ANONYMIZED   NUMBER(1)       DEFAULT 1 NOT NULL,
  WISH         VARCHAR2(500)   NULL,
  MODEL        VARCHAR2(128)   NULL,
  DOSSIER      CLOB            NULL,
  RESPONSE     CLOB            NULL,
  CONSTRAINT PK_AGRO_AI_ANALYSES    PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_AI_ANA_CUST    FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_AGRO_AI_ANA_CUST ON AGRO_AI_ANALYSES(CUSTOMER_ID, CREATED_AT DESC);

CREATE TABLE AGRO_AI_CHAT_MESSAGES (
  ID           NUMBER(10)      NOT NULL,
  CREATED_AT   DATE            DEFAULT SYSDATE NOT NULL,
  CUSTOMER_ID  NUMBER(10)      NOT NULL,
  ROLE         VARCHAR2(16)    NOT NULL,
  CONTENT      CLOB            NULL,
  CONSTRAINT PK_AGRO_AI_CHAT        PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_AI_CHAT_CUST   FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_AGRO_AI_CHAT_ROLE  CHECK (ROLE IN ('user', 'assistant'))
);

CREATE INDEX IDX_AGRO_AI_CHAT_CUST ON AGRO_AI_CHAT_MESSAGES(CUSTOMER_ID, ID);
