-- ============================================================
-- AGRO_CRM_APP_USERS         — bot users (Telegram chat identities).
--                     One row per unique TG chat. Может ссылаться
--                     на AGRO_CUSTOMERS, если менеджер связал.
-- CRM_TG_BINDINGS   — invite-токены, одноразовые приглашения от
--                     менеджера клиенту: /start <token> в боте
--                     привязывает AGRO_CRM_APP_USERS к AGRO_CUSTOMERS.
-- ============================================================

-- ---------------- AGRO_CRM_APP_USERS -----------------------------------
CREATE SEQUENCE AGRO_CRM_APP_USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_APP_USERS (
  ID                  NUMBER          NOT NULL,
  TELEGRAM_CHAT_ID    NUMBER          NOT NULL,
  TELEGRAM_USERNAME   VARCHAR2(100),
  TELEGRAM_FIRST_NAME VARCHAR2(200),
  TELEGRAM_LAST_NAME  VARCHAR2(200),
  CUSTOMER_ID         NUMBER,
  STATUS              VARCHAR2(20)    DEFAULT 'pending' NOT NULL,
  LANGUAGE_CODE       VARCHAR2(10),
  FIRST_SEEN          TIMESTAMP       DEFAULT SYSTIMESTAMP,
  LAST_SEEN           TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_APP_USERS              PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_CRM_APP_USERS_CHATID       UNIQUE (TELEGRAM_CHAT_ID),
  CONSTRAINT FK_AGRO_CRM_APP_USERS_CUSTOMER     FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT CK_AGRO_CRM_APP_USERS_STATUS       CHECK (STATUS IN ('pending','linked','blocked'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_APP_USERS_BI
  BEFORE INSERT ON AGRO_CRM_APP_USERS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_APP_USERS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_AGRO_CRM_APP_USERS_CUSTOMER ON AGRO_CRM_APP_USERS(CUSTOMER_ID);
/

-- ---------------- CRM_TG_BINDINGS -----------------------------
CREATE SEQUENCE CRM_TG_BINDINGS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE CRM_TG_BINDINGS (
  ID            NUMBER          NOT NULL,
  CUSTOMER_ID   NUMBER          NOT NULL,
  INVITE_TOKEN  VARCHAR2(64)    NOT NULL,
  STATUS        VARCHAR2(20)    DEFAULT 'pending' NOT NULL,
  APP_USER_ID   NUMBER,
  CREATED_BY    NUMBER,
  CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
  BOUND_AT      TIMESTAMP,
  EXPIRES_AT    TIMESTAMP,
  CONSTRAINT PK_CRM_TG_BINDINGS         PRIMARY KEY (ID),
  CONSTRAINT UQ_CRM_TG_BINDINGS_TOKEN   UNIQUE (INVITE_TOKEN),
  CONSTRAINT FK_CRM_TGB_CUSTOMER        FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT FK_CRM_TGB_APPUSER         FOREIGN KEY (APP_USER_ID) REFERENCES AGRO_CRM_APP_USERS(ID),
  CONSTRAINT FK_CRM_TGB_CREATEDBY       FOREIGN KEY (CREATED_BY) REFERENCES AGRO_USERS(ID),
  CONSTRAINT CK_CRM_TGB_STATUS          CHECK (STATUS IN ('pending','bound','revoked','expired'))
);
/

CREATE OR REPLACE TRIGGER CRM_TG_BINDINGS_BI
  BEFORE INSERT ON CRM_TG_BINDINGS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CRM_TG_BINDINGS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_CRM_TGB_CUSTOMER ON CRM_TG_BINDINGS(CUSTOMER_ID);
/
CREATE INDEX IX_CRM_TGB_STATUS   ON CRM_TG_BINDINGS(STATUS);
/

COMMIT;
/
