-- 57_crm_deals.sql
-- AGRO_CRM_DEALS — CRM pipeline deals linked to customers.
-- Stages: lead → qualified → proposal → negotiation → won / lost

CREATE SEQUENCE AGRO_CRM_DEALS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE AGRO_CRM_DEALS (
  ID             NUMBER          NOT NULL,
  TITLE          VARCHAR2(300)   NOT NULL,
  CUSTOMER_ID    NUMBER          NOT NULL,
  STAGE          VARCHAR2(20)    DEFAULT 'lead',
  AMOUNT         NUMBER(14,2),
  CURRENCY       VARCHAR2(3)     DEFAULT 'MDL',
  PROBABILITY    NUMBER(3,0)     DEFAULT 10,
  EXPECTED_DATE  DATE,
  ASSIGNED_TO    VARCHAR2(100),
  NOTES          VARCHAR2(2000),
  CREATED_BY     VARCHAR2(100),
  CREATED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP,
  UPDATED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CLOSED_AT      TIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_DEALS     PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_CD_CUSTOMER   FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT CK_AGRO_CD_STAGE      CHECK (STAGE IN ('lead','qualified','proposal','negotiation','won','lost')),
  CONSTRAINT CK_AGRO_CD_PROB       CHECK (PROBABILITY BETWEEN 0 AND 100)
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_DEALS_BI
  BEFORE INSERT ON AGRO_CRM_DEALS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := AGRO_CRM_DEALS_SEQ.NEXTVAL;
  END IF;
  :NEW.CREATED_AT := SYSTIMESTAMP;
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER AGRO_CRM_DEALS_BU
  BEFORE UPDATE ON AGRO_CRM_DEALS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
  IF :NEW.STAGE IN ('won','lost') AND :OLD.STAGE NOT IN ('won','lost') THEN
    :NEW.CLOSED_AT := SYSTIMESTAMP;
  END IF;
END;
/

CREATE INDEX IX_AGRO_CD_CUSTOMER ON AGRO_CRM_DEALS (CUSTOMER_ID);
CREATE INDEX IX_AGRO_CD_STAGE    ON AGRO_CRM_DEALS (STAGE);
CREATE INDEX IX_AGRO_CD_UPDATED  ON AGRO_CRM_DEALS (UPDATED_AT DESC);
