-- 58_crm_tasks.sql
-- AGRO_CRM_TASKS — manager tasks optionally linked to customers and/or deals.

CREATE SEQUENCE AGRO_CRM_TASKS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE AGRO_CRM_TASKS (
  ID           NUMBER          NOT NULL,
  TITLE        VARCHAR2(500)   NOT NULL,
  CUSTOMER_ID  NUMBER,
  DEAL_ID      NUMBER,
  ASSIGNED_TO  VARCHAR2(100),
  DUE_DATE     DATE,
  PRIORITY     VARCHAR2(10)    DEFAULT 'normal',
  STATUS       VARCHAR2(20)    DEFAULT 'open',
  NOTES        VARCHAR2(2000),
  CREATED_BY   VARCHAR2(100),
  CREATED_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP,
  COMPLETED_AT TIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_TASKS    PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_CT_CUSTOMER  FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT FK_AGRO_CT_DEAL      FOREIGN KEY (DEAL_ID) REFERENCES AGRO_CRM_DEALS(ID) ON DELETE SET NULL,
  CONSTRAINT CK_AGRO_CT_PRIORITY  CHECK (PRIORITY IN ('low','normal','high','urgent')),
  CONSTRAINT CK_AGRO_CT_STATUS    CHECK (STATUS IN ('open','in_progress','done','cancelled'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_TASKS_BI
  BEFORE INSERT ON AGRO_CRM_TASKS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := AGRO_CRM_TASKS_SEQ.NEXTVAL;
  END IF;
  :NEW.CREATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER AGRO_CRM_TASKS_BU
  BEFORE UPDATE ON AGRO_CRM_TASKS FOR EACH ROW
BEGIN
  IF :NEW.STATUS = 'done' AND :OLD.STATUS != 'done' THEN
    :NEW.COMPLETED_AT := SYSTIMESTAMP;
  END IF;
END;
/

CREATE INDEX IX_AGRO_CT_CUSTOMER ON AGRO_CRM_TASKS (CUSTOMER_ID);
CREATE INDEX IX_AGRO_CT_DEAL     ON AGRO_CRM_TASKS (DEAL_ID);
CREATE INDEX IX_AGRO_CT_STATUS   ON AGRO_CRM_TASKS (STATUS);
CREATE INDEX IX_AGRO_CT_DUE      ON AGRO_CRM_TASKS (DUE_DATE);
