-- 63_crm_attachments.sql
-- CRM file attachments stored in AWS S3, metadata in Oracle.

CREATE SEQUENCE AGRO_CRM_ATTACHMENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE AGRO_CRM_ATTACHMENTS (
  ID           NUMBER          NOT NULL,
  ENTITY_TYPE  VARCHAR2(20)    NOT NULL,
  ENTITY_ID    NUMBER          NOT NULL,
  FILE_NAME    VARCHAR2(300)   NOT NULL,
  FILE_TYPE    VARCHAR2(100),
  FILE_SIZE    NUMBER,
  S3_KEY       VARCHAR2(500)   NOT NULL,
  UPLOADED_BY  VARCHAR2(100),
  UPLOADED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_ATTACHMENTS   PRIMARY KEY (ID),
  CONSTRAINT CK_AGRO_CRM_ATT_ETYPE     CHECK (ENTITY_TYPE IN ('customer','task'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_ATTACHMENTS_BI
  BEFORE INSERT ON AGRO_CRM_ATTACHMENTS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := AGRO_CRM_ATTACHMENTS_SEQ.NEXTVAL;
  END IF;
END;
/

CREATE INDEX IX_AGRO_CRM_ATT_ENTITY ON AGRO_CRM_ATTACHMENTS (ENTITY_TYPE, ENTITY_ID);
