CREATE TABLE AGRO_CRM_AUDIT_LOG (
  ID           NUMBER        NOT NULL,
  ENTITY_TYPE  VARCHAR2(30)  NOT NULL,
  ENTITY_ID    NUMBER        NOT NULL,
  ENTITY_NAME  VARCHAR2(255),
  ACTION       VARCHAR2(20)  NOT NULL,
  CHANGED_BY   VARCHAR2(100),
  CHANGED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  OLD_VALUES   CLOB,
  NEW_VALUES   CLOB,
  CONSTRAINT PK_AGRO_CRM_AUDIT PRIMARY KEY (ID)
);

CREATE SEQUENCE AGRO_CRM_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER AGRO_CRM_AUDIT_BI
  BEFORE INSERT ON AGRO_CRM_AUDIT_LOG
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT AGRO_CRM_AUDIT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_AUDIT_ENTITY ON AGRO_CRM_AUDIT_LOG (ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_AUDIT_CHANGED_AT ON AGRO_CRM_AUDIT_LOG (CHANGED_AT DESC);
