CREATE TABLE AGRO_CRM_LEADS (
  ID           NUMBER         NOT NULL,
  NAME         VARCHAR2(255)  NOT NULL,
  COMPANY      VARCHAR2(255),
  PHONE        VARCHAR2(50),
  EMAIL        VARCHAR2(255),
  SOURCE       VARCHAR2(50)   DEFAULT 'other',
  STATUS       VARCHAR2(30)   DEFAULT 'new',
  NOTES        CLOB,
  ASSIGNED_TO  VARCHAR2(100),
  CUSTOMER_ID  NUMBER,
  CREATED_BY   VARCHAR2(100),
  CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_AGRO_CRM_LEADS PRIMARY KEY (ID),
  CONSTRAINT CHK_LEAD_STATUS   CHECK (STATUS IN ('new','contacted','qualified','proposal','won','lost')),
  CONSTRAINT CHK_LEAD_SOURCE   CHECK (SOURCE IN ('web','referral','cold_call','social','exhibition','other'))
);

CREATE SEQUENCE AGRO_CRM_LEADS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER AGRO_CRM_LEADS_BI
  BEFORE INSERT ON AGRO_CRM_LEADS
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT AGRO_CRM_LEADS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_LEADS_STATUS ON AGRO_CRM_LEADS (STATUS);
CREATE INDEX IDX_LEADS_ASSIGNED ON AGRO_CRM_LEADS (ASSIGNED_TO);
