-- ============================================================
-- CRM_USERS — CRM staff accounts (login / role)
-- Copy of AGRO_USERS structure, independent table.
-- Roles: admin | manager
-- Password stored as bcrypt hash (cost 10).
-- ============================================================

CREATE SEQUENCE AGRO_CRM_USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_USERS (
  ID             NUMBER          NOT NULL,
  USERNAME       VARCHAR2(100)   NOT NULL,
  PASSWORD_HASH  VARCHAR2(200)   NOT NULL,
  FIRST_NAME     VARCHAR2(100),
  LAST_NAME      VARCHAR2(100),
  ROLE           VARCHAR2(20)    DEFAULT 'manager' NOT NULL,
  ACTIVE         CHAR(1)         DEFAULT 'Y'       NOT NULL,
  CREATED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_USERS          PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_CRM_USERS_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CK_AGRO_CRM_USERS_ROLE     CHECK (ROLE IN ('admin','manager')),
  CONSTRAINT CK_AGRO_CRM_USERS_ACTIVE   CHECK (ACTIVE IN ('Y','N'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_USERS_BI
  BEFORE INSERT ON AGRO_CRM_USERS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_USERS_SEQ.NEXTVAL;
END;
/

-- Copy existing users from AGRO_USERS
INSERT INTO AGRO_CRM_USERS (ID, USERNAME, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ROLE, ACTIVE, CREATED_AT)
SELECT ID, USERNAME, PASSWORD_HASH, FIRST_NAME, LAST_NAME,
       CASE WHEN ROLE IN ('admin','manager') THEN ROLE ELSE 'manager' END,
       ACTIVE, CREATED_AT
  FROM AGRO_USERS;
/

COMMIT;
/
