BEGIN EXECUTE IMMEDIATE 'DROP TABLE AGRO_CRM_USERS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CRM_USERS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE AGRO_CRM_USERS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
