-- ============================================================
-- CRM Oracle — consolidated schema
-- DB: Oracle 11g (una.md:4024/cloudbd.world, user: dippfruct)
-- Depends on: 35_agro_tables.sql (AGRO_CUSTOMERS, AGRO_WAREHOUSES, ...)
--
-- Tables (18):
--   AGRO_USERS                  — CRM staff (authentication)
--   AGRO_ACTIVITY_LOG           — user action audit log
--   AGRO_CRM_APP_USERS          — Telegram bot users
--   AGRO_CRM_TG_BINDINGS        — invite tokens for customer linking
--   AGRO_CRM_APP_USER_EVENTS    — bot user event history
--   AGRO_CRM_CHAT_MESSAGES      — bot chat messages
--   AGRO_CRM_TASKS              — manager tasks
--   AGRO_CRM_ACTIVITIES         — calls / meetings / notes
--   AGRO_CRM_AUTOMATION_RULES   — automation rules
--   AGRO_CRM_AUTOMATION_LOG     — automation execution log
--   AGRO_CRM_ATTACHMENTS        — S3 file attachments
--   AGRO_CRM_AUDIT_LOG          — CRM entity change log
--   AGRO_CRM_PIPELINES          — sales pipelines
--   AGRO_CRM_LEADS              — leads / prospects
--   AGRO_CRM_LOYALTY_TIERS      — loyalty program levels
--   AGRO_CRM_LOYALTY_MEMBERS    — loyalty program members
--   AGRO_CRM_LOYALTY_TX         — loyalty point transactions
--   AGRO_CRM_EMAILS             — Gmail sync emails
-- ============================================================

-- ============================================================
-- 1. AGRO_USERS — CRM staff authentication
-- ============================================================

DECLARE v INT;
BEGIN
  SELECT COUNT(*) INTO v FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'AGRO_USERS_SEQ';
  IF v = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE AGRO_USERS_SEQ START WITH 100 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE v INT;
BEGIN
  SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = 'AGRO_USERS';
  IF v = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE AGRO_USERS (
        ID            NUMBER          NOT NULL,
        USERNAME      VARCHAR2(100)   NOT NULL,
        PASSWORD_HASH VARCHAR2(255)   NOT NULL,
        FULL_NAME     VARCHAR2(200),
        ROLE          VARCHAR2(20)    DEFAULT ''operator'' NOT NULL,
        ACTIVE        CHAR(1)         DEFAULT ''Y''        NOT NULL,
        CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
        CONSTRAINT PK_AGRO_USERS         PRIMARY KEY (ID),
        CONSTRAINT UQ_AGRO_USERS_NAME    UNIQUE (USERNAME),
        CONSTRAINT CK_AGRO_USERS_ROLE    CHECK (ROLE   IN (''admin'',''manager'',''operator'',''viewer'')),
        CONSTRAINT CK_AGRO_USERS_ACTIVE  CHECK (ACTIVE IN (''Y'',''N''))
      )';
  END IF;
END;
/

-- Idempotent fixes for existing deployments (table pre-existed with different schema)
BEGIN
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AGRO_USERS ADD FULL_NAME VARCHAR2(200)';           EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AGRO_USERS MODIFY PASSWORD_HASH VARCHAR2(255)';    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AGRO_USERS DROP CONSTRAINT CK_AGRO_USERS_ROLE';   EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE AGRO_USERS ADD CONSTRAINT CK_AGRO_USERS_ROLE CHECK (ROLE IN (''admin'',''manager'',''operator'',''viewer''))'; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

-- Seed admin (default password: Artgranit2026#)
MERGE INTO AGRO_USERS tgt
USING (SELECT 'admin' AS USERNAME FROM DUAL) src
  ON (tgt.USERNAME = src.USERNAME)
WHEN MATCHED THEN
  UPDATE SET FULL_NAME     = NVL(tgt.FULL_NAME, 'Administrator'),
             ROLE          = 'admin',
             ACTIVE        = 'Y',
             PASSWORD_HASH = 'scrypt:32768:8:1$MfVkxevw2v4tWUmQ$ba59e8cdb96cd765fbb57b051256ff8bcf2ee205a475bc4e100e30fc1964de556136defdb181a05c46900058e79d650f90ec90e792ac8bb7ae1cfbaed12130d2'
WHEN NOT MATCHED THEN
  INSERT (ID, USERNAME, FULL_NAME, ROLE, ACTIVE, PASSWORD_HASH)
  VALUES (AGRO_USERS_SEQ.NEXTVAL, 'admin', 'Administrator', 'admin', 'Y',
          'scrypt:32768:8:1$MfVkxevw2v4tWUmQ$ba59e8cdb96cd765fbb57b051256ff8bcf2ee205a475bc4e100e30fc1964de556136defdb181a05c46900058e79d650f90ec90e792ac8bb7ae1cfbaed12130d2');
/

-- ============================================================
-- 2. AGRO_ACTIVITY_LOG — user action audit log (idempotent)
-- ============================================================

DECLARE v INT;
BEGIN
  SELECT COUNT(*) INTO v FROM USER_TABLES WHERE TABLE_NAME = 'AGRO_ACTIVITY_LOG';
  IF v = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE AGRO_ACTIVITY_LOG (
        ID          NUMBER          NOT NULL,
        LOG_TIME    DATE            DEFAULT SYSDATE NOT NULL,
        ACTOR       VARCHAR2(100),
        ACTION      VARCHAR2(50)    NOT NULL,
        ENTITY      VARCHAR2(80)    NOT NULL,
        ENTITY_ID   NUMBER,
        DESCRIPTION VARCHAR2(500),
        CONSTRAINT PK_AGRO_ACTIVITY_LOG PRIMARY KEY (ID)
      )';
  END IF;
END;
/

DECLARE v INT;
BEGIN
  SELECT COUNT(*) INTO v FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'AGRO_ACTIVITY_LOG_SEQ';
  IF v = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE AGRO_ACTIVITY_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

-- ============================================================
-- 3. AGRO_CRM_APP_USERS — Telegram bot users
-- ============================================================

CREATE SEQUENCE AGRO_CRM_APP_USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_APP_USERS (
  ID                  NUMBER          NOT NULL,
  TELEGRAM_CHAT_ID    NUMBER          NOT NULL,
  TELEGRAM_USERNAME   VARCHAR2(100),
  TELEGRAM_FIRST_NAME VARCHAR2(200),
  TELEGRAM_LAST_NAME  VARCHAR2(200),
  CUSTOMER_ID         NUMBER,
  STATUS              VARCHAR2(20)    DEFAULT 'pending' NOT NULL,
  LANGUAGE_CODE       VARCHAR2(10),
  FIRST_SEEN          TIMESTAMP       DEFAULT SYSTIMESTAMP,
  LAST_SEEN           TIMESTAMP       DEFAULT SYSTIMESTAMP,
  LAST_MESSAGE_AT     TIMESTAMP,
  UNREAD_COUNT        NUMBER          DEFAULT 0 NOT NULL,
  ARCHIVED            CHAR(1)         DEFAULT 'N' NOT NULL,
  CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_APP_USERS          PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_CRM_APP_USERS_CHATID   UNIQUE (TELEGRAM_CHAT_ID),
  CONSTRAINT FK_AGRO_CRM_APP_USERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT CK_AGRO_CRM_APP_USERS_STATUS   CHECK (STATUS   IN ('pending','linked','blocked')),
  CONSTRAINT CK_AGRO_CRM_APP_USERS_ARCHIVED CHECK (ARCHIVED IN ('Y','N'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_APP_USERS_BI
  BEFORE INSERT ON AGRO_CRM_APP_USERS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_APP_USERS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_AGRO_CRM_APP_USERS_CUSTOMER ON AGRO_CRM_APP_USERS(CUSTOMER_ID);
/

-- ============================================================
-- 4. AGRO_CRM_TG_BINDINGS — invite tokens for customer linking
-- ============================================================

CREATE SEQUENCE AGRO_CRM_TG_BINDINGS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_TG_BINDINGS (
  ID            NUMBER          NOT NULL,
  CUSTOMER_ID   NUMBER          NOT NULL,
  INVITE_TOKEN  VARCHAR2(64)    NOT NULL,
  STATUS        VARCHAR2(20)    DEFAULT 'pending' NOT NULL,
  APP_USER_ID   NUMBER,
  CREATED_BY    NUMBER,
  CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
  BOUND_AT      TIMESTAMP,
  EXPIRES_AT    TIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_TG_BINDINGS       PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_CRM_TGB_TOKEN         UNIQUE (INVITE_TOKEN),
  CONSTRAINT FK_AGRO_CRM_TGB_CUSTOMER      FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT FK_AGRO_CRM_TGB_APPUSER       FOREIGN KEY (APP_USER_ID) REFERENCES AGRO_CRM_APP_USERS(ID),
  CONSTRAINT FK_AGRO_CRM_TGB_CREATEDBY     FOREIGN KEY (CREATED_BY)  REFERENCES AGRO_USERS(ID),
  CONSTRAINT CK_AGRO_CRM_TGB_STATUS        CHECK (STATUS IN ('pending','bound','revoked','expired'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_TG_BINDINGS_BI
  BEFORE INSERT ON AGRO_CRM_TG_BINDINGS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_TG_BINDINGS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_AGRO_CRM_TGB_CUSTOMER ON AGRO_CRM_TG_BINDINGS(CUSTOMER_ID);
/
CREATE INDEX IX_AGRO_CRM_TGB_STATUS   ON AGRO_CRM_TG_BINDINGS(STATUS);
/

-- ============================================================
-- 5. AGRO_CRM_APP_USER_EVENTS — bot user event history
-- ============================================================

CREATE SEQUENCE AGRO_CRM_APP_USER_EVENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_APP_USER_EVENTS (
  ID           NUMBER          NOT NULL,
  APP_USER_ID  NUMBER          NOT NULL,
  EVENT_TYPE   VARCHAR2(30)    NOT NULL,
  PAYLOAD      VARCHAR2(2000),
  ACTOR_USER   NUMBER,
  CREATED_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_APP_USER_EVENTS PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_CRM_AUE_USER        FOREIGN KEY (APP_USER_ID) REFERENCES AGRO_CRM_APP_USERS(ID),
  CONSTRAINT FK_AGRO_CRM_AUE_ACTOR       FOREIGN KEY (ACTOR_USER)  REFERENCES AGRO_USERS(ID),
  CONSTRAINT CK_AGRO_CRM_AUE_TYPE        CHECK (EVENT_TYPE IN (
    'start','start_with_token','linked','unlinked','blocked','unblocked',
    'message_in','message_out','archived','unarchived','act_sent'
  ))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_APP_USER_EVENTS_BI
  BEFORE INSERT ON AGRO_CRM_APP_USER_EVENTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_APP_USER_EVENTS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_AGRO_CRM_AUE_USER    ON AGRO_CRM_APP_USER_EVENTS(APP_USER_ID);
/
CREATE INDEX IX_AGRO_CRM_AUE_CREATED ON AGRO_CRM_APP_USER_EVENTS(CREATED_AT);
/

-- ============================================================
-- 6. AGRO_CRM_CHAT_MESSAGES — bot chat messages
-- ============================================================

CREATE SEQUENCE AGRO_CRM_CHAT_MESSAGES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_CHAT_MESSAGES (
  ID             NUMBER          NOT NULL,
  APP_USER_ID    NUMBER          NOT NULL,
  DIRECTION      VARCHAR2(3)     NOT NULL,
  BODY           CLOB,
  TG_MESSAGE_ID  NUMBER,
  FILE_ID        VARCHAR2(200),
  FILE_TYPE      VARCHAR2(20),
  STATUS         VARCHAR2(20)    DEFAULT 'sent' NOT NULL,
  SENT_BY_USER   NUMBER,
  ERROR          VARCHAR2(2000),
  CREATED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_CHAT_MESSAGES  PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_CRM_CM_APPUSER     FOREIGN KEY (APP_USER_ID)  REFERENCES AGRO_CRM_APP_USERS(ID),
  CONSTRAINT FK_AGRO_CRM_CM_SENTBY      FOREIGN KEY (SENT_BY_USER) REFERENCES AGRO_USERS(ID),
  CONSTRAINT CK_AGRO_CRM_CM_DIR         CHECK (DIRECTION IN ('in','out')),
  CONSTRAINT CK_AGRO_CRM_CM_FTYPE       CHECK (FILE_TYPE IS NULL OR FILE_TYPE IN (
    'document','photo','voice','video','audio','sticker'
  )),
  CONSTRAINT CK_AGRO_CRM_CM_STATUS      CHECK (STATUS IN ('pending','sent','delivered','read','failed'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_CHAT_MESSAGES_BI
  BEFORE INSERT ON AGRO_CRM_CHAT_MESSAGES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_CHAT_MESSAGES_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_AGRO_CRM_CM_APPUSER ON AGRO_CRM_CHAT_MESSAGES(APP_USER_ID, CREATED_AT);
/

-- ============================================================
-- 7. AGRO_CRM_TASKS — manager tasks
-- ============================================================

CREATE SEQUENCE AGRO_CRM_TASKS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_TASKS (
  ID           NUMBER          NOT NULL,
  TITLE        VARCHAR2(500)   NOT NULL,
  CUSTOMER_ID  NUMBER,
  DEAL_ID      NUMBER,
  ASSIGNED_TO  VARCHAR2(100),
  DUE_DATE     DATE,
  PRIORITY     VARCHAR2(10)    DEFAULT 'normal',
  STATUS       VARCHAR2(20)    DEFAULT 'open',
  NOTES        VARCHAR2(2000),
  CREATED_BY   VARCHAR2(100),
  CREATED_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP,
  COMPLETED_AT TIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_TASKS   PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_CT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT CK_AGRO_CT_PRIORITY CHECK (PRIORITY IN ('low','normal','high','urgent')),
  CONSTRAINT CK_AGRO_CT_STATUS   CHECK (STATUS   IN ('open','in_progress','done','cancelled'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_TASKS_BI
  BEFORE INSERT ON AGRO_CRM_TASKS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := AGRO_CRM_TASKS_SEQ.NEXTVAL;
  END IF;
  :NEW.CREATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER AGRO_CRM_TASKS_BU
  BEFORE UPDATE ON AGRO_CRM_TASKS FOR EACH ROW
BEGIN
  IF :NEW.STATUS = 'done' AND :OLD.STATUS != 'done' THEN
    :NEW.COMPLETED_AT := SYSTIMESTAMP;
  END IF;
END;
/

CREATE INDEX IX_AGRO_CT_CUSTOMER ON AGRO_CRM_TASKS(CUSTOMER_ID);
/
CREATE INDEX IX_AGRO_CT_STATUS   ON AGRO_CRM_TASKS(STATUS);
/
CREATE INDEX IX_AGRO_CT_DUE      ON AGRO_CRM_TASKS(DUE_DATE);
/

-- ============================================================
-- 8. AGRO_CRM_ACTIVITIES — calls / meetings / notes
-- ============================================================

CREATE SEQUENCE AGRO_CRM_ACTIVITIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_ACTIVITIES (
  ID           NUMBER          NOT NULL,
  CUSTOMER_ID  NUMBER          NOT NULL,
  DEAL_ID      NUMBER,
  ACT_TYPE     VARCHAR2(20)    DEFAULT 'note' NOT NULL,
  BODY         VARCHAR2(4000),
  OUTCOME      VARCHAR2(20),
  CREATED_BY   VARCHAR2(100),
  CREATED_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_ACTIVITIES PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_CA_CUSTOMER    FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT CK_AGRO_CA_TYPE        CHECK (ACT_TYPE IN ('call','meeting','note','email','other')),
  CONSTRAINT CK_AGRO_CA_OUTCOME     CHECK (OUTCOME IS NULL OR OUTCOME IN (
    'reached','no_answer','voicemail','busy','completed','cancelled'
  ))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_ACTIVITIES_BI
  BEFORE INSERT ON AGRO_CRM_ACTIVITIES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_ACTIVITIES_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_AGRO_CA_CUSTOMER ON AGRO_CRM_ACTIVITIES(CUSTOMER_ID, CREATED_AT);
/

-- ============================================================
-- 9. AGRO_CRM_AUTOMATION_RULES + AGRO_CRM_AUTOMATION_LOG
-- ============================================================

CREATE SEQUENCE AGRO_CRM_AUTO_RULES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE AGRO_CRM_AUTO_LOG_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_AUTOMATION_RULES (
  ID               NUMBER          NOT NULL,
  NAME             VARCHAR2(300)   NOT NULL,
  TRIGGER_TYPE     VARCHAR2(30)    DEFAULT 'no_order_days' NOT NULL,
  CONDITION_DAYS   NUMBER          DEFAULT 30              NOT NULL,
  ACTION_TYPE      VARCHAR2(20)    DEFAULT 'tg_message'    NOT NULL,
  MESSAGE_TEMPLATE VARCHAR2(2000),
  TASK_TITLE       VARCHAR2(500),
  COOLDOWN_DAYS    NUMBER          DEFAULT 7               NOT NULL,
  SEGMENT          VARCHAR2(20)    DEFAULT 'all'           NOT NULL,
  ACTIVE           CHAR(1)         DEFAULT 'Y'             NOT NULL,
  CREATED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_AUTO_RULES PRIMARY KEY (ID),
  CONSTRAINT CK_AGRO_CAR_TRIGGER    CHECK (TRIGGER_TYPE IN ('no_order_days')),
  CONSTRAINT CK_AGRO_CAR_ACTION     CHECK (ACTION_TYPE  IN ('tg_message','manager_task')),
  CONSTRAINT CK_AGRO_CAR_SEGMENT    CHECK (SEGMENT      IN ('all','vip','active','sleeping','churned')),
  CONSTRAINT CK_AGRO_CAR_ACTIVE     CHECK (ACTIVE       IN ('Y','N'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_AUTO_RULES_BI
  BEFORE INSERT ON AGRO_CRM_AUTOMATION_RULES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_AUTO_RULES_SEQ.NEXTVAL;
END;
/

CREATE TABLE AGRO_CRM_AUTOMATION_LOG (
  ID          NUMBER          NOT NULL,
  RULE_ID     NUMBER          NOT NULL,
  CUSTOMER_ID NUMBER          NOT NULL,
  ACTION_TYPE VARCHAR2(20),
  RESULT      VARCHAR2(10)    DEFAULT 'success' NOT NULL,
  DETAILS     VARCHAR2(2000),
  FIRED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_AUTO_LOG  PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_CAL_RULE      FOREIGN KEY (RULE_ID)     REFERENCES AGRO_CRM_AUTOMATION_RULES(ID),
  CONSTRAINT FK_AGRO_CAL_CUSTOMER  FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT CK_AGRO_CAL_RESULT    CHECK (RESULT IN ('success','error','skipped'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_AUTO_LOG_BI
  BEFORE INSERT ON AGRO_CRM_AUTOMATION_LOG FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_AUTO_LOG_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_AGRO_CAL_RULE ON AGRO_CRM_AUTOMATION_LOG(RULE_ID,     FIRED_AT);
/
CREATE INDEX IX_AGRO_CAL_CUST ON AGRO_CRM_AUTOMATION_LOG(CUSTOMER_ID, FIRED_AT);
/

-- Seed automation rules (idempotent by NAME)
INSERT INTO AGRO_CRM_AUTOMATION_RULES
  (NAME, TRIGGER_TYPE, CONDITION_DAYS, ACTION_TYPE, MESSAGE_TEMPLATE, COOLDOWN_DAYS, SEGMENT)
SELECT 'Нет заказов 30 дней → напомнить клиенту',
       'no_order_days', 30, 'tg_message',
       'Здравствуйте, {{customer_name}}! Давно не видели вас среди наших покупателей. Если нужна свежая продукция — мы готовы помочь. Напишите нам!',
       14, 'all'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AGRO_CRM_AUTOMATION_RULES WHERE NAME = 'Нет заказов 30 дней → напомнить клиенту');
/

INSERT INTO AGRO_CRM_AUTOMATION_RULES
  (NAME, TRIGGER_TYPE, CONDITION_DAYS, ACTION_TYPE, TASK_TITLE, COOLDOWN_DAYS, SEGMENT)
SELECT 'VIP не покупал 14 дней → задача менеджеру',
       'no_order_days', 14, 'manager_task',
       'Позвонить VIP-клиенту {{customer_name}}: нет заказов {{days_since}} дней',
       7, 'vip'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AGRO_CRM_AUTOMATION_RULES WHERE NAME = 'VIP не покупал 14 дней → задача менеджеру');
/

COMMIT;
/

-- ============================================================
-- 10. AGRO_CRM_ATTACHMENTS — S3 file attachments
-- ============================================================

CREATE SEQUENCE AGRO_CRM_ATTACHMENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_ATTACHMENTS (
  ID           NUMBER          NOT NULL,
  ENTITY_TYPE  VARCHAR2(20)    NOT NULL,
  ENTITY_ID    NUMBER          NOT NULL,
  FILE_NAME    VARCHAR2(300)   NOT NULL,
  FILE_TYPE    VARCHAR2(100),
  FILE_SIZE    NUMBER,
  S3_KEY       VARCHAR2(500)   NOT NULL,
  UPLOADED_BY  VARCHAR2(100),
  UPLOADED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRM_ATTACHMENTS PRIMARY KEY (ID),
  CONSTRAINT CK_AGRO_CRM_ATT_ETYPE   CHECK (ENTITY_TYPE IN ('customer','task'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_ATTACHMENTS_BI
  BEFORE INSERT ON AGRO_CRM_ATTACHMENTS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := AGRO_CRM_ATTACHMENTS_SEQ.NEXTVAL;
  END IF;
END;
/

CREATE INDEX IX_AGRO_CRM_ATT_ENTITY ON AGRO_CRM_ATTACHMENTS(ENTITY_TYPE, ENTITY_ID);
/

-- ============================================================
-- 11. AGRO_CRM_AUDIT_LOG — CRM entity change log
-- ============================================================

CREATE SEQUENCE AGRO_CRM_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_AUDIT_LOG (
  ID           NUMBER        NOT NULL,
  ENTITY_TYPE  VARCHAR2(30)  NOT NULL,
  ENTITY_ID    NUMBER        NOT NULL,
  ENTITY_NAME  VARCHAR2(255),
  ACTION       VARCHAR2(20)  NOT NULL,
  CHANGED_BY   VARCHAR2(100),
  CHANGED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  OLD_VALUES   CLOB,
  NEW_VALUES   CLOB,
  CONSTRAINT PK_AGRO_CRM_AUDIT PRIMARY KEY (ID)
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_AUDIT_BI
  BEFORE INSERT ON AGRO_CRM_AUDIT_LOG FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT AGRO_CRM_AUDIT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_AUDIT_ENTITY     ON AGRO_CRM_AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
/
CREATE INDEX IDX_AUDIT_CHANGED_AT ON AGRO_CRM_AUDIT_LOG(CHANGED_AT DESC);
/

-- ============================================================
-- 12. AGRO_CRM_PIPELINES — sales pipelines
-- ============================================================

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE AGRO_CRM_PIPELINES (
      ID          NUMBER         NOT NULL,
      NAME        VARCHAR2(100)  NOT NULL,
      DESCRIPTION VARCHAR2(500),
      IS_DEFAULT  NUMBER(1)      DEFAULT 0,
      CREATED_AT  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
      CREATED_BY  VARCHAR2(100),
      CONSTRAINT AGRO_CRM_PIPELINES_PK PRIMARY KEY (ID)
    )
  ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE AGRO_CRM_PIPELINES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER AGRO_CRM_PIPELINES_TRG
    BEFORE INSERT ON AGRO_CRM_PIPELINES FOR EACH ROW
    BEGIN
      IF :NEW.ID IS NULL THEN
        SELECT AGRO_CRM_PIPELINES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
      END IF;
    END;
  ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'INSERT INTO AGRO_CRM_PIPELINES (NAME, DESCRIPTION, IS_DEFAULT)
    SELECT ''Основная'', ''Стандартная воронка продаж'', 1 FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM AGRO_CRM_PIPELINES)';
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================
-- 13. AGRO_CRM_LEADS — leads / prospects
-- ============================================================

CREATE SEQUENCE AGRO_CRM_LEADS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE AGRO_CRM_LEADS (
  ID           NUMBER         NOT NULL,
  NAME         VARCHAR2(255)  NOT NULL,
  COMPANY      VARCHAR2(255),
  PHONE        VARCHAR2(50),
  EMAIL        VARCHAR2(255),
  SOURCE       VARCHAR2(50)   DEFAULT 'other',
  STATUS       VARCHAR2(30)   DEFAULT 'new',
  NOTES        CLOB,
  ASSIGNED_TO  VARCHAR2(100),
  CUSTOMER_ID  NUMBER,
  PIPELINE_ID  NUMBER,
  CREATED_BY   VARCHAR2(100),
  CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_AGRO_CRM_LEADS PRIMARY KEY (ID),
  CONSTRAINT CHK_LEAD_STATUS   CHECK (STATUS IN ('new','contacted','qualified','proposal','won','lost')),
  CONSTRAINT CHK_LEAD_SOURCE   CHECK (SOURCE IN ('web','referral','cold_call','social','exhibition','other'))
);
/

CREATE OR REPLACE TRIGGER AGRO_CRM_LEADS_BI
  BEFORE INSERT ON AGRO_CRM_LEADS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT AGRO_CRM_LEADS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_LEADS_STATUS   ON AGRO_CRM_LEADS(STATUS);
/
CREATE INDEX IDX_LEADS_ASSIGNED ON AGRO_CRM_LEADS(ASSIGNED_TO);
/

-- ============================================================
-- 14. AGRO_CRM_LOYALTY_TIERS — loyalty program levels
-- ============================================================

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE AGRO_CRM_LOYALTY_TIERS (
      ID         NUMBER        NOT NULL,
      NAME       VARCHAR2(50)  NOT NULL,
      MIN_POINTS NUMBER        DEFAULT 0,
      COLOR      VARCHAR2(20)  DEFAULT ''gray'',
      SORT_ORDER NUMBER        DEFAULT 0,
      CONSTRAINT AGRO_CRM_TIERS_PK PRIMARY KEY (ID)
    )
  ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE AGRO_CRM_TIERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER AGRO_CRM_TIERS_TRG
    BEFORE INSERT ON AGRO_CRM_LOYALTY_TIERS FOR EACH ROW
    BEGIN
      IF :NEW.ID IS NULL THEN
        SELECT AGRO_CRM_TIERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
      END IF;
    END;
  ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'INSERT INTO AGRO_CRM_LOYALTY_TIERS (NAME, MIN_POINTS, COLOR, SORT_ORDER)
    SELECT ''Бронза'',  0,     ''amber'',  1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM AGRO_CRM_LOYALTY_TIERS WHERE NAME = ''Бронза'')';
  EXECUTE IMMEDIATE 'INSERT INTO AGRO_CRM_LOYALTY_TIERS (NAME, MIN_POINTS, COLOR, SORT_ORDER)
    SELECT ''Серебро'', 1000,  ''slate'',  2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM AGRO_CRM_LOYALTY_TIERS WHERE NAME = ''Серебро'')';
  EXECUTE IMMEDIATE 'INSERT INTO AGRO_CRM_LOYALTY_TIERS (NAME, MIN_POINTS, COLOR, SORT_ORDER)
    SELECT ''Золото'',  5000,  ''yellow'', 3 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM AGRO_CRM_LOYALTY_TIERS WHERE NAME = ''Золото'')';
  EXECUTE IMMEDIATE 'INSERT INTO AGRO_CRM_LOYALTY_TIERS (NAME, MIN_POINTS, COLOR, SORT_ORDER)
    SELECT ''Платина'', 10000, ''cyan'',   4 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM AGRO_CRM_LOYALTY_TIERS WHERE NAME = ''Платина'')';
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================
-- 15. AGRO_CRM_LOYALTY_MEMBERS — loyalty program members
-- ============================================================

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE AGRO_CRM_LOYALTY_MEMBERS (
      ID           NUMBER        NOT NULL,
      CUSTOMER_ID  NUMBER        NOT NULL,
      TOTAL_POINTS NUMBER        DEFAULT 0,
      TIER_ID      NUMBER,
      ENROLLED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT AGRO_CRM_LM_PK      PRIMARY KEY (ID),
      CONSTRAINT AGRO_CRM_LM_CUST_UQ UNIQUE (CUSTOMER_ID)
    )
  ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE AGRO_CRM_LMEMBERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER AGRO_CRM_LMEMBERS_TRG
    BEFORE INSERT ON AGRO_CRM_LOYALTY_MEMBERS FOR EACH ROW
    BEGIN
      IF :NEW.ID IS NULL THEN
        SELECT AGRO_CRM_LMEMBERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
      END IF;
    END;
  ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================
-- 16. AGRO_CRM_LOYALTY_TX — loyalty point transactions
-- ============================================================

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE AGRO_CRM_LOYALTY_TX (
      ID          NUMBER        NOT NULL,
      MEMBER_ID   NUMBER        NOT NULL,
      POINTS      NUMBER        NOT NULL,
      TX_TYPE     VARCHAR2(30),
      DESCRIPTION VARCHAR2(500),
      REF_ID      NUMBER,
      CREATED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT AGRO_CRM_LTX_PK PRIMARY KEY (ID)
    )
  ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE AGRO_CRM_LTX_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER AGRO_CRM_LTX_TRG
    BEFORE INSERT ON AGRO_CRM_LOYALTY_TX FOR EACH ROW
    BEGIN
      IF :NEW.ID IS NULL THEN
        SELECT AGRO_CRM_LTX_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
      END IF;
    END;
  ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================
-- 17. AGRO_CRM_EMAILS — Gmail sync emails
-- ============================================================

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE AGRO_CRM_EMAILS (
      ID          NUMBER         NOT NULL,
      MESSAGE_ID  VARCHAR2(500),
      DIRECTION   VARCHAR2(3)    NOT NULL,
      FROM_ADDR   VARCHAR2(500),
      TO_ADDR     VARCHAR2(500),
      SUBJECT     VARCHAR2(1000),
      BODY_TEXT   CLOB,
      LEAD_ID     NUMBER,
      CUSTOMER_ID NUMBER,
      SENT_AT     TIMESTAMP,
      SYNCED_AT   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT AGRO_CRM_EMAILS_PK PRIMARY KEY (ID)
    )
  ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE AGRO_CRM_EMAILS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER AGRO_CRM_EMAILS_TRG
    BEFORE INSERT ON AGRO_CRM_EMAILS FOR EACH ROW
    BEGIN
      IF :NEW.ID IS NULL THEN
        SELECT AGRO_CRM_EMAILS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
      END IF;
    END;
  ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX AGRO_CRM_EMAILS_MSGID ON AGRO_CRM_EMAILS(MESSAGE_ID)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

SELECT 'OK: CRM schema ready' AS STATUS FROM DUAL;
