

-- ============================================================
-- STEP 1: RENAME TABLES
-- ============================================================

RENAME AGRO_CRM_APP_USERS           TO AGRO_CRM_AGRO_CRM_APP_USERS;
RENAME CRM_TG_BINDINGS     TO AGRO_CRM_TG_BINDINGS;
RENAME CRM_APP_USER_EVENTS TO AGRO_CRM_APP_USER_EVENTS;
RENAME CRM_CHAT_MESSAGES   TO AGRO_CRM_CHAT_MESSAGES;

-- ============================================================
-- STEP 2: ПЕРЕСОЗДАТЬ SEQUENCES
-- START WITH = LAST_NUMBER + 100 (запас)
-- AGRO_CRM_APP_USERS_SEQ        LAST_NUMBER=5   -> 105
-- CRM_TG_BINDINGS_SEQ  LAST_NUMBER=2   -> 102
-- CRM_APP_USER_EVENTS_SEQ LAST_NUMBER=21 -> 121
-- CRM_CHAT_MESSAGES_SEQ LAST_NUMBER=23  -> 123
-- ============================================================

DROP SEQUENCE AGRO_CRM_APP_USERS_SEQ;
CREATE SEQUENCE AGRO_CRM_AGRO_CRM_APP_USERS_SEQ
  START WITH 105 INCREMENT BY 1 NOCACHE NOCYCLE;

DROP SEQUENCE CRM_TG_BINDINGS_SEQ;
CREATE SEQUENCE AGRO_CRM_TG_BINDINGS_SEQ
  START WITH 102 INCREMENT BY 1 NOCACHE NOCYCLE;

DROP SEQUENCE CRM_APP_USER_EVENTS_SEQ;
CREATE SEQUENCE AGRO_CRM_APP_USER_EVENTS_SEQ
  START WITH 121 INCREMENT BY 1 NOCACHE NOCYCLE;

DROP SEQUENCE CRM_CHAT_MESSAGES_SEQ;
CREATE SEQUENCE AGRO_CRM_CHAT_MESSAGES_SEQ
  START WITH 123 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- STEP 3: УДАЛИТЬ СТАРЫЕ TRIGGERS, СОЗДАТЬ НОВЫЕ
-- ============================================================

DROP TRIGGER AGRO_CRM_APP_USERS_BI;
DROP TRIGGER CRM_TG_BINDINGS_BI;
DROP TRIGGER CRM_APP_USER_EVENTS_BI;
DROP TRIGGER CRM_CHAT_MESSAGES_BI;

CREATE OR REPLACE TRIGGER AGRO_CRM_AGRO_CRM_APP_USERS_BI
  BEFORE INSERT ON AGRO_CRM_AGRO_CRM_APP_USERS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_AGRO_CRM_APP_USERS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER AGRO_CRM_TG_BINDINGS_BI
  BEFORE INSERT ON AGRO_CRM_TG_BINDINGS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_TG_BINDINGS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER AGRO_CRM_APP_USER_EVENTS_BI
  BEFORE INSERT ON AGRO_CRM_APP_USER_EVENTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_APP_USER_EVENTS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER AGRO_CRM_CHAT_MESSAGES_BI
  BEFORE INSERT ON AGRO_CRM_CHAT_MESSAGES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRM_CHAT_MESSAGES_SEQ.NEXTVAL;
END;
/

-- ============================================================
-- STEP 4: ПЕРЕСОЗДАТЬ INDEXES
-- ============================================================

DROP INDEX IX_AGRO_CRM_APP_USERS_CUSTOMER;
CREATE INDEX IX_AGRO_CRM_AGRO_CRM_APP_USERS_CUSTOMER ON AGRO_CRM_AGRO_CRM_APP_USERS(CUSTOMER_ID);

DROP INDEX IX_CRM_TGB_CUSTOMER;
CREATE INDEX IX_AGRO_CRM_TGB_CUSTOMER ON AGRO_CRM_TG_BINDINGS(CUSTOMER_ID);

DROP INDEX IX_CRM_TGB_STATUS;
CREATE INDEX IX_AGRO_CRM_TGB_STATUS ON AGRO_CRM_TG_BINDINGS(STATUS);

DROP INDEX IX_CRM_AUE_USER;
CREATE INDEX IX_AGRO_CRM_AUE_USER ON AGRO_CRM_APP_USER_EVENTS(APP_USER_ID);

DROP INDEX IX_CRM_AUE_CREATED;
CREATE INDEX IX_AGRO_CRM_AUE_CREATED ON AGRO_CRM_APP_USER_EVENTS(CREATED_AT);

DROP INDEX IX_CRM_CM_APPUSER;
CREATE INDEX IX_AGRO_CRM_CM_APPUSER ON AGRO_CRM_CHAT_MESSAGES(APP_USER_ID, CREATED_AT);

-- ============================================================
-- STEP 5: RENAME CONSTRAINTS
-- ============================================================

ALTER TABLE AGRO_CRM_AGRO_CRM_APP_USERS RENAME CONSTRAINT PK_AGRO_CRM_APP_USERS          TO PK_AGRO_CRM_AGRO_CRM_APP_USERS;
ALTER TABLE AGRO_CRM_AGRO_CRM_APP_USERS RENAME CONSTRAINT UQ_AGRO_CRM_APP_USERS_CHATID   TO UQ_AGRO_CRM_AGRO_CRM_APP_USERS_CHATID;
ALTER TABLE AGRO_CRM_AGRO_CRM_APP_USERS RENAME CONSTRAINT FK_AGRO_CRM_APP_USERS_CUSTOMER TO FK_AGRO_CRM_AGRO_CRM_APP_USERS_CUSTOMER;
ALTER TABLE AGRO_CRM_AGRO_CRM_APP_USERS RENAME CONSTRAINT CK_AGRO_CRM_APP_USERS_STATUS   TO CK_AGRO_CRM_AGRO_CRM_APP_USERS_STATUS;
ALTER TABLE AGRO_CRM_AGRO_CRM_APP_USERS RENAME CONSTRAINT CK_AGRO_CRM_APP_USERS_ARCHIVED TO CK_AGRO_CRM_AGRO_CRM_APP_USERS_ARCHIVED;

ALTER TABLE AGRO_CRM_TG_BINDINGS RENAME CONSTRAINT PK_CRM_TG_BINDINGS       TO PK_AGRO_CRM_TG_BINDINGS;
ALTER TABLE AGRO_CRM_TG_BINDINGS RENAME CONSTRAINT UQ_CRM_TG_BINDINGS_TOKEN TO UQ_AGRO_CRM_TG_BINDINGS_TOKEN;
ALTER TABLE AGRO_CRM_TG_BINDINGS RENAME CONSTRAINT FK_CRM_TGB_CUSTOMER      TO FK_AGRO_CRM_TGB_CUSTOMER;
ALTER TABLE AGRO_CRM_TG_BINDINGS RENAME CONSTRAINT FK_CRM_TGB_APPUSER       TO FK_AGRO_CRM_TGB_APPUSER;
ALTER TABLE AGRO_CRM_TG_BINDINGS RENAME CONSTRAINT FK_CRM_TGB_CREATEDBY     TO FK_AGRO_CRM_TGB_CREATEDBY;
ALTER TABLE AGRO_CRM_TG_BINDINGS RENAME CONSTRAINT CK_CRM_TGB_STATUS        TO CK_AGRO_CRM_TGB_STATUS;

ALTER TABLE AGRO_CRM_APP_USER_EVENTS RENAME CONSTRAINT PK_CRM_APP_USER_EVENTS TO PK_AGRO_CRM_APP_USER_EVENTS;
ALTER TABLE AGRO_CRM_APP_USER_EVENTS RENAME CONSTRAINT FK_CRM_AUE_USER        TO FK_AGRO_CRM_AUE_USER;
ALTER TABLE AGRO_CRM_APP_USER_EVENTS RENAME CONSTRAINT FK_CRM_AUE_ACTOR       TO FK_AGRO_CRM_AUE_ACTOR;
ALTER TABLE AGRO_CRM_APP_USER_EVENTS RENAME CONSTRAINT CK_CRM_AUE_TYPE        TO CK_AGRO_CRM_AUE_TYPE;

ALTER TABLE AGRO_CRM_CHAT_MESSAGES RENAME CONSTRAINT PK_CRM_CHAT_MESSAGES TO PK_AGRO_CRM_CHAT_MESSAGES;
ALTER TABLE AGRO_CRM_CHAT_MESSAGES RENAME CONSTRAINT FK_CRM_CM_APPUSER    TO FK_AGRO_CRM_CM_APPUSER;
ALTER TABLE AGRO_CRM_CHAT_MESSAGES RENAME CONSTRAINT FK_CRM_CM_SENTBY     TO FK_AGRO_CRM_CM_SENTBY;
ALTER TABLE AGRO_CRM_CHAT_MESSAGES RENAME CONSTRAINT CK_CRM_CM_DIR        TO CK_AGRO_CRM_CM_DIR;
ALTER TABLE AGRO_CRM_CHAT_MESSAGES RENAME CONSTRAINT CK_CRM_CM_FTYPE      TO CK_AGRO_CRM_CM_FTYPE;
ALTER TABLE AGRO_CRM_CHAT_MESSAGES RENAME CONSTRAINT CK_CRM_CM_STATUS     TO CK_AGRO_CRM_CM_STATUS;

-- ============================================================
-- DONE
-- ============================================================
